name: Chatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.20=py311hc63dfec_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6d0c2b6_0
  - ipykernel=7.2.0=pyh5552912_1
  - ipython=9.10.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h37d8d59_0
  - libcxx=19.1.7=haebbb44_3
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libffi=3.4.4=hecd8cb5_1
  - libsodium=1.0.20=hfdf4475_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.1=hb6871ef_1
  - packaging=26.0=pyhcf101f3_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py311ha332486_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.13=hbff2529_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pyzmq=27.1.0=py311h0ab6910_0
  - readline=8.3=h49f2429_0
  - setuptools=78.1.1=py311hecd8cb5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hc8b0dd6_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h3a5a201_0
  - tornado=6.5.4=py311ha2bb86f_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=he532380_0
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - wheel=0.45.1=py311hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zeromq=4.3.5=h6c33b1e_9
  - zlib=1.2.13=h4b97444_1
  - pip:
      - aiofiles==24.1.0
      - aiosqlite==0.22.1
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - brotli==1.2.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - distro==1.9.0
      - fastapi==0.128.6
      - ffmpy==1.0.0
      - filelock==3.20.3
      - fsspec==2026.2.0
      - gradio==6.5.1
      - gradio-client==2.0.3
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.13.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==1.2.9
      - langchain-core==1.2.9
      - langchain-openai==1.1.8
      - langgraph==1.0.8
      - langgraph-checkpoint==4.0.0
      - langgraph-checkpoint-sqlite==3.0.3
      - langgraph-prebuilt==1.0.7
      - langgraph-sdk==0.3.4
      - langsmith==0.7.0
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - numpy==2.4.2
      - openai==2.17.0
      - orjson==3.11.7
      - ormsgpack==1.12.2
      - pandas==3.0.0
      - pillow==12.1.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pydub==0.25.1
      - python-dotenv==1.2.1
      - python-multipart==0.0.22
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2026.1.15
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.3.2
      - safehttpx==0.1.7
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sqlite-vec==0.1.6
      - starlette==0.52.1
      - tenacity==9.1.4
      - tiktoken==0.12.0
      - tomlkit==0.13.3
      - tqdm==4.67.3
      - typer==0.21.1
      - typer-slim==0.21.1
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - uuid-utils==0.14.0
      - uvicorn==0.40.0
      - xxhash==3.6.0
      - zstandard==0.25.0
prefix: /opt/anaconda3/envs/Chatbot
